### ISSUE TITLE
DTDs needed

### ISSUE THREAD

**Issue by rdelong73** [oxygenxml/dita-export-map#2]
This plugin works great, however, the export should include the DTDs (IMO).

**Comment by raducoravu** [comment]
Thanks for the kind words.
The plugin cannot know where the DTDs are located because they are usually resolved via an XML catalog.
Usually the DTDs are distributed as part of a certain DITA OT plugin so the build files can be modified to also include that plugin in the ZIP file. This could be done either as a separate parameter which could be set when exporting or by directly modifying the build file.
